spring:
  application:
    name: payment-order-management

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/payment_order_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:16379}

server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:change-this-development-secret-key-to-a-long-random-value-please}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}

  cache:
    product-ttl-seconds: ${PRODUCT_CACHE_TTL_SECONDS:300}


management:
  endpoints:
    web:
      exposure:
        include: health
